# Resources:
# - Exemple docker compose: https://github.com/adorsys/keycloak-config-cli/blob/main/docker-compose.yml
# - Documentation de la config du dashboard keycloak: https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/index.html
# - Documentation API REST: https://documenter.getpostman.com/view/7294517/SzmfZHnd
# - Solution pour la configuration finale: https://github.com/keycloak/keycloak/discussions/13516
# - Solution pour installer keycloak en SSL: https://slash-root.fr/keycloak-installation-avec-docker-et-reverse-proxy-ssl-nginx/
# - Un genre d'explication de config keyclaok: https://www.youtube.com/watch?v=duawSV69LDI&
# - Toutes les versions de keycloak : https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest

services:

  keycloak:
    container_name: ${CONTAINER_NAME}
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: INFO
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_ADMIN}
      KC_DB_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres-server
      ROOT_LOGLEVEL: INFO
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-server
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_ADMIN}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8085:8080"
    command:
      - --verbose
      - start
    depends_on:
      - postgres-server

  postgres-server:
    container_name: postgres-server
    image: "postgres:16.3-alpine"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - data_volume:/var/lib/postgresql/data/
      - sql_volume:/docker-entrypoint-initdb.d/:ro

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:latest"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres-server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-server

volumes:
  data_volume:
  sql_volume:

#server {
#  listen 80;
#  server_name secure-connect.devpapangue.com;
#  rewrite ^ https://secure-connect.devpapangue.com permanent;
#}
#
#server {
#  listen 443 ssl;
#  server_name secure-connect.devpapangue.com;
#  ssl_certificate /etc/letsencrypt/live/secure-connect.devpapangue.com/fullchain.pem;
#  ssl_certificate_key /etc/letsencrypt/live/secure-connect.devpapangue.com/privkey.pem;
#  ssl_session_cache builtin:1000 shared:SSL:10m;
#  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
#  ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
#  ssl_prefer_server_ciphers on;
#
#  location / {
#    proxy_set_header Host $host;
#    proxy_set_header X-Real-IP $remote_addr;
#    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#    proxy_set_header X-Forwarded-Proto $scheme;
#    proxy_pass http://51.77.140.50:8085;
#  }
#}

#  build                   Creates a new and optimized server image.
#  start                   Start the server.
#  start-dev               Start the server in development mode.
#  export                  Export data from realms to a file or directory.
#  import                  Import data from a directory or a file.
#  show-config             Print out the current configuration.
#  tools                   Utilities for use and interaction with the server.
#  completion            Generate bash/zsh completion script for kc.sh.

