# Resources:
# - Exemple docker compose: https://github.com/adorsys/keycloak-config-cli/blob/main/docker-compose.yml
# - Documentation de la config du dashboard keycloak: https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/index.html
# - Documentation API REST: https://documenter.getpostman.com/view/7294517/SzmfZHnd

version: "3.9"

services:

  keycloak:
    container_name: ${CONTAINER_NAME}
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - "8085:8080"
      - "8787:8787"
    command:
      - start-dev
      - --features admin-fine-grained-authz

  keycloak-legacy:
    container_name: ${CONTAINER_NAME}-legacy
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}-legacy
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    volumes:
      - legacy_volume:/opt/jboss/keycloak/providers/
    ports:
      - "8081:8080"
      - "8788:8787"
    command:
      - "-c"
      - "standalone.xml"
      - "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"

volumes:
  legacy_volume:
